name: example-config
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  separate-specs-v9:
    # example where we pass specs to run via multiple lines
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: ./
        with:
          working-directory: src/frontend
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:4004'
          config: baseUrl=http://localhost:4004
          spec: |
            cypress/e2e/spec.cy.ts
            cypress/e2e/spec.cy.ts
