name: Cypress Tests

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Config Node env
        run: |
          cd ${{ github.repository }}/src/frontend
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: true
          build: npm run build
          start: npm start
