name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/-2, lts/-1]
        cypress-version: [10, 11, 12]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          install: false
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm i cypress@${{ matrix.cypress-version }}
      - run: npm run build --if-present
      - run: npm test
