name: example-edge
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress info
        uses: ./
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npm run build
          working-directory: src/frontend
