name: Checks

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.19.0]
    container: cypress/base:${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Install examples dependencies
        run: npm run start

      - name: Tests
        run: npm run test
