name: Checks

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.19.0]
    container: cypress/base:${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd src/frontend
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: run portal
        run: |
          cd src/frontend
          npm run start &
          sleep 30
      - name: open
        uses: cypress-io/github-action@v5
        with:
          install: false
          env: host=api.dev.local,port=4004
          
      - name: test e2e
        run: |
          cd src/frontend
          npm run cypress:run
          

